# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_auto_20160330_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'STATE_ACCEPTED'), ('WAITING', 'STATE_WAITING'), ('REFUSED', 'STATE_REFUSED')], default='WAITING', max_length=3),
        ),
        migrations.AlterField(
            model_name='customer',
            name='adresse1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='adresse2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='offer',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.CharField(max_length=500),
        ),
    ]
