# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_auto_20160330_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'STATE_ACCEPTED'), ('WAITING', 'STATE_WAITING'), ('REFUSED', 'STATE_REFUSED')], default='WAITING', max_length=10),
        ),
    ]
